#' Save Processed Weather Data to APSIM .met format (Self-Documenting)
#'
#' @param met_list List. Output from createWeatherFile() containing data, tav, amp, mapped_cols, and missing_vars.
#' @param folder_path Character. Directory to save the .met file.
#' @param file_name Character. Target file name (e.g., "WaggaWagga2024.met").
#' @param lat Numeric. Latitude for the header.
#' @param lon Numeric. Longitude for the header.
#' @return Character. The full path to the saved file.
#' @export
save_met_file <- function(met_list, folder_path, file_name, lat, lon) {
  
  dir.create(folder_path, showWarnings = FALSE, recursive = TRUE)
  outfileName <- file.path(folder_path, file_name)
  
  # ------------------------------------------------------------------
  # 1. CONSOLE REPORTING & WARNINGS
  # ------------------------------------------------------------------
  message(sprintf("Building APSIM .met file: %s", file_name))
  
  if (!is.null(met_list$mapped_cols)) {
    for (var in names(met_list$mapped_cols)) {
      message(sprintf("  [\u2713] Included %s (mapped from Excel col: '%s')", toupper(var), met_list$mapped_cols[[var]]))
    }
  }
  
  # Throw warning if optional variables are missing
  if (!is.null(met_list$missing_vars) && length(met_list$missing_vars) > 0) {
    warning(sprintf(
      "Met file '%s' generated WITHOUT optional variables: %s", 
      file_name, paste(toupper(met_list$missing_vars), collapse = ", ")
    ), call. = FALSE)
  }
  
  # ------------------------------------------------------------------
  # 2. DYNAMIC APSIM UNITS & HEADERS
  # ------------------------------------------------------------------
  unit_map <- c(
    year = "()", 
    day  = "()", 
    radn = "(MJ/m^2)", 
    maxt = "(oC)", 
    mint = "(oC)", 
    rain = "(mm)", 
    vp   = "(hPa)", 
    et   = "(mm)"
  )
  
  cols_present <- names(met_list$data)
  
  # Dynamically pull the exact names and units for the data we actually have
  header_names <- paste(cols_present, collapse = "  ")
  header_units <- paste(unname(unit_map[cols_present]), collapse = "  ")
  
  # Safely construct mapping comments
  if (!is.null(met_list$mapped_cols) && length(met_list$mapped_cols) > 0) {
    mapping_comments <- paste0("! ", toupper(names(met_list$mapped_cols)), " extracted from raw column: '", unlist(met_list$mapped_cols), "'")
    mapping_comments_text <- paste(mapping_comments, collapse = "\n")
  } else {
    mapping_comments_text <- "! Warning: Source mapping metadata not available."
  }
  
  # ------------------------------------------------------------------
  # 3. BUILD AND WRITE FILE
  # ------------------------------------------------------------------
  header_met <- glue::glue("
[weather.met.weather]
! Data generated by automated _targets pipeline
{mapping_comments_text}

latitude = {lat}  (DECIMAL DEGREES)
longitude = {lon}   (DECIMAL DEGREES)
tav = {met_list$tav} (oC) ! Annual average ambient temperature.
amp = {met_list$amp} (oC) ! Annual amplitude in mean monthly temperature.

{header_names}
{header_units}
")
  
  writeLines(header_met, outfileName)
  
  # Write the dataframe natively 
  write.table(
    met_list$data,
    file = outfileName,
    append = TRUE,
    sep = " ",
    quote = FALSE,
    col.names = FALSE,
    row.names = FALSE,
    na = "NaN" 
  )
  
  return(outfileName)
}